### ISSUE TITLE
pdf link on readme file times out immediately

### ISSUE THREAD

**Issue by JordanCWalsh** [SkRobo/rplidar#1]
your pdf link is broken or times out immediately, refreshing my wifi connection and ip address does not help, im on most recent Chrome browser for Windows 10

**Comment by newpavlov** [comment]
Link works for me. Probably some problems on the side of slamtec hosting. For the time being you can download this pdf from [archive.org](http://web.archive.org/web/20161105070926/http://www.slamtec.com/download/lidar/documents/en-us/rplidar_interface_protocol_en.pdf).
