### ISSUE TITLE
/dev/ttyUSB0 not found

### ISSUE THREAD

**Issue by fishworx** [SkRobo/rplidar#29]
Hi, I'm running python3 on raspberry pi3b+.

The example code cant find the /dev/ttyUSB0 file.

I did the pip3 install as per the instructions. Is there any pre-requisite installs? Lidar is new out of the box.

![lidar](https://user-images.githubusercontent.com/29113771/64587580-33b44580-d3e3-11e9-811b-c85284f77a8f.jpg)

**Comment by newpavlov** [comment]
`/dev/ttyUSB0` is just an example path common for UART2USB on desktop Linux. I am not familiar with RPi3, but try a different path. IIUC with a correct configuration it [should be](https://raspberrypi.stackexchange.com/questions/45570/how-do-i-make-serial-work-on-the-raspberry-pi3-pi3b-pizerow) `/dev/serial0`.

**Comment by fishworx** [comment]
all fixed, was not using the correct usb cable..... need to use a usb cable with power and data...
