### ISSUE TITLE
What does it mean output of record_measurments.py ?

### ISSUE THREAD

**Issue by durmusgulbahar** [SkRobo/rplidar#41]
**I have data but what does [XXX] blocks mean in output.txt file from record_measurments.py ?**

![out](https://user-images.githubusercontent.com/44837495/124888211-90ccb280-dfde-11eb-8c11-40b6c250b211.png)

**Comment by newpavlov** [comment]
See `iter_measurments` [docs](https://github.com/SkoltechRobotics/rplidar/blob/master/rplidar.py#L277-L299). It should be strength of reflected light, though I am not sure why you get such uniform values.

**Comment by durmusgulbahar** [comment]
I found in iter_measures() function in rplidar.py file.

_Yields
        ------
        new_scan : bool
            True if measures belongs to a new scan
        quality : int
            Reflected laser pulse strength
        angle : float
            The measure heading angle in degree unit [0, 360)
        distance : float
            Measured object distance related to the sensor's rotation center.
            In millimeter unit. Set to 0 when measure is invalid.
        '''_
