### ISSUE TITLE
means of "new_scan" and "quality" yields of iter_measures() method ?

### ISSUE THREAD

**Issue by durmusgulbahar** [SkRobo/rplidar#42]
1- "new_scan" is always **False** in txt file. What does that mean ? 
2- What is the range of "quality" ? . What does it mean literally ? How can i improve it ?
    "quality" always  is one of either 0 or 15 for every scan. 
_Yields
        ------
        new_scan : bool
            True if measures belongs to a new scan
        quality : int
            Reflected laser pulse strength
        angle : float
            The measure heading angle in degree unit [0, 360)
        distance : float
            Measured object distance related to the sensor's rotation center.
            In millimeter unit. Set to 0 when measure is invalid.
        '''_

**Comment by newpavlov** [comment]
Those values are reported directly by sensor, so please consult slamtec documents for their meaning since it may vary for different sensor models. Raw serial stream is decoded in [this function](https://github.com/SkoltechRobotics/rplidar/blob/master/rplidar.py#L72-L84) if you are interested.
